
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox;

	private global::Gtk.HBox hbox;

	private global::Gtk.Button buttonAdelante;

	private global::Gtk.Table table;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox = new global::Gtk.VBox();
		this.vbox.Name = "vbox";
		this.vbox.Spacing = 6;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox = new global::Gtk.HBox();
		this.hbox.Name = "hbox";
		this.hbox.Spacing = 6;
		// Container child hbox.Gtk.Box+BoxChild
		this.buttonAdelante = new global::Gtk.Button();
		this.buttonAdelante.CanFocus = true;
		this.buttonAdelante.Name = "buttonAdelante";
		this.buttonAdelante.UseUnderline = true;
		this.buttonAdelante.Label = global::Mono.Unix.Catalog.GetString("Adelante");
		this.hbox.Add(this.buttonAdelante);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox[this.buttonAdelante]));
		w1.Position = 2;
		w1.Expand = false;
		w1.Fill = false;
		this.vbox.Add(this.hbox);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hbox]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.table = new global::Gtk.Table(((uint)(9)), ((uint)(10)), true);
		this.table.Name = "table";
		this.table.RowSpacing = ((uint)(6));
		this.table.ColumnSpacing = ((uint)(6));
		this.vbox.Add(this.table);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox[this.table]));
		w3.Position = 1;
		this.Add(this.vbox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
